name: deso_sdk
description: Unofficial Dart SDK for Decentralized Social / DeSo.org
version: 0.1.0+4
homepage: https://github.com/oliverbytes/deso_sdk

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  dio: ^4.0.6
  logger: ^1.1.0
  either_option: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
